version: "3.8"
services:
  marketplace_web:
    build: ../
    ports: ["3101:3101"]
    depends_on: [postgres, redis]
    env_file: ./../scripts/.env.postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: marketuser
      POSTGRES_PASSWORD: marketpass
      POSTGRES_DB: marketplace
    volumes:
      - /volume1/docker/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: always
    ports: ["6379:6379"]

  killbill:
    image: killbill/killbill:latest
    restart: always
    ports: ["8088:8080"]
    environment:
      - KILLBILL_DATABASE_URL=jdbc:postgresql://postgres:5432/killbill
      - KILLBILL_DATABASE_USER=marketuser
      - KILLBILL_DATABASE_PASSWORD=marketpass
