// utils/password.js — updated to use native bcrypt
// Compatible with existing $2b$10$... hashes generated by bcrypt

import bcrypt from 'bcrypt';

/**
 * Hash a plain text password using bcrypt.
 * @param {string} password
 * @returns {Promise<string>} bcrypt hash
 */
export async function hashPassword(password) {
  const salt = await bcrypt.genSalt(10);
  return bcrypt.hash(password, salt);
}

/**
 * Verify a password against a bcrypt hash.
 * @param {string} password - plain text input
 * @param {string} hash - stored bcrypt hash
 * @returns {Promise<boolean>} true if match
 */
export async function verifyPassword(password, hash) {
  return bcrypt.compare(password, hash);
}
